name: Android Release

# 1
on:
  # 2
  push:
    branches:
      - master

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: windows-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      # 10
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.0.0"
          channel: 'stable'
          cache: true
      # 12
      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build apk --release

      # 8
      - name: Upload Android Release
        uses: actions/upload-artifact@v2
          with:
            name: android-release
            path: build/app/outputs/apk/release/app-release.apk